version: '3.4'

services:
  blazorsozluk.webapi:
    image: ${DOCKER_REGISTRY-}blazorsozlukwebapi
    build:
      context: .
      dockerfile: src/Api/WebApi/BlazorSozluk.WebApi/Dockerfile

  blazorsozluk.webapp:
    image: ${DOCKER_REGISTRY-}blazorsozlukwebapp
    build:
      context: .
      dockerfile: src/Clients/BlazorWeb/BlazorSozluk.WebApp/Dockerfile




  blazorsozluk.projections.voteservice:
    image: ${DOCKER_REGISTRY-}blazorsozlukprojectionsvoteservice
    build:
      context: .
      dockerfile: src/Projections/BlazorSozluk.Projections.VoteService/Dockerfile


  blazorsozluk.projections.userservice:
    image: ${DOCKER_REGISTRY-}blazorsozlukprojectionsuserservice
    build:
      context: .
      dockerfile: src/Projections/BlazorSozluk.Projections.UserService/Dockerfile


  blazorsozluk.projections.favoriteservice:
    image: ${DOCKER_REGISTRY-}blazorsozlukprojectionsfavoriteservice
    build:
      context: .
      dockerfile: src/Projections/BlazorSozluk.Projections.FavoriteService/Dockerfile


